# Generated by Django 2.2.12 on 2020-04-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='foto'),
        ),
    ]
