# Generated by Django 2.2.12 on 2020-04-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200410_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='comprovante'),
        ),
    ]
